### ISSUE TITLE
Invalid Return Type

### ISSUE THREAD

**Issue by rwrobe** [moderntribe/square1-global-docker#12]
**Describe the bug**

Running the bash install script in the installation instructions, I get the following:

```sh
Downloading so.phar to /usr/local/bin/so, enter your password when requested.
PHP Fatal error:  Uncaught TypeError: Return value of Tribe\SquareOne\Models\OperatingSystem::getLinuxFlavor() must be of the type string, bool returned in phar:///home/wardrobe/.config/squareone/bin/so/src/Models/OperatingSystem.php:48
Stack trace:
#0 phar:///home/wardrobe/.config/squareone/bin/so/src/Hooks/CertificateHandler.php(51): Tribe\SquareOne\Models\OperatingSystem->getLinuxFlavor()
#1 [internal function]: Tribe\SquareOne\Hooks\CertificateHandler->setDependencies()
#2 phar:///home/wardrobe/.config/squareone/bin/so/vendor/league/container/src/Inflector/Inflector.php(100): call_user_func_array()
#3 phar:///home/wardrobe/.config/squareone/bin/so/vendor/league/container/src/Inflector/InflectorAggregate.php(43): League\Container\Inflector\Inflector->inflect()
#4 phar:///home/wardrobe/.config/squareone/bin/so/vendor/league/container/src/Container.php(290): League\Container\Inflector\InflectorAggregate->inflect()
#5 phar:///home/wardrobe/.config/squareone/bin/so/vendor/league/container/src/Container.php(85): League\Container in phar:///home/wardrobe/.config/squareone/bin/so/src/Models/OperatingSystem.php on line 48
```

Clearly this is due to my wacky distro, Zorin, but changing the type of the return when the distro isn't found will also prevent this error. See referenced PR.

**To Reproduce**
Ran install line in ZorinOS

**Expected behavior**
Installation succeeds

**System Configuration:**
 - OS: ZorinOS 15.2
 - PHP Version 7.4.4

**Comment by rwrobe** [comment]
PR #13

**Comment by defunctl** [comment]
Thanks for this Rob! Please add the proper paths to the config file here: https://github.com/moderntribe/square1-global-docker/blob/master/config/squareone.yml#L57

and

https://github.com/moderntribe/square1-global-docker/blob/master/config/squareone.yml#L74

**Comment by defunctl** [comment]
Fixed in https://github.com/moderntribe/square1-global-docker/pull/30
